<?= $this->doctype(); ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Programowanie Aplikacji Internetowych')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css')
        ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css')
    ?>

    <?= $this->headScript()
        ->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js')
        ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js')
    ?>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Programowanie Aplikacji Internetowych</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <?= $this->navigation('admin_navigation')
                ->menu()
                ->setPartial('menu')
                ->render();
            ?>
            <span class="navbar-text ml-auto">
                Zalogowany:
                <strong>
                    <?=$this->identity()->imie ?>
                    <?=$this->identity()->nazwisko ?>
                </strong>
            </span>
        </div>
    </nav>

    <div class="container">
        <div class="pt-3">
            <?=$this->fm() ?>

            <div id="content">
                <?=$this->content; ?>
            </div>
        </div>
        <hr>
        <footer>
            <p class="text-secondary text-center">Wyższa Szkoła Informatyki Stosowanej i Zarządzania <?= date('Y') ?>/<?= date('Y') + 1 ?></p>
        </footer>
    </div> <!-- /container -->
    <?= $this->inlineScript() ?>
</body>

</html>