<h1>Szczegóły autora</h1>

<table class="table">
    <thead>
    <tr>
        <th>Id</th>
        <th>Imię</th>
        <th>Nazwisko</th>
        <th>Szczegóły</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><?= $autor->id ?></td>
        <td><?= $autor->imie ?></td>
        <td><?= $autor->nazwisko ?></td>
        <td><?= $autor->opis ?></td>
        <td>
            <a href="<?= $this->url('autorzy', ['action' => 'lista']) ?>"
                title="wróć do listy">powrót</a>
        </td>
    </tr>
    </tbody>
</table>